#!/bin/bash
# Include Beaker environment
./usr/bin/rhts-environment.sh || exit 1
./usr/share/beakerlib/beakerlib.sh || exit 1



rlJournalStart

    rlPhaseStartTest
        rlRun "echo /"HelloWorld/"" 0 "Print out HelloWorld"
    rlPhaseEnd

    rlJournalPrintText
    
rlJournalEnd
